package:
  image: golang:1.24.5
  stage: build
  script:
    - apt-get update && apt-get install jq ca-certificates curl gnupg -y
    - install -m 0755 -d /etc/apt/keyrings
    - curl -fsSL https://download.docker.com/linux/debian/gpg | gpg --dearmor -o /etc/apt/keyrings/docker.gpg
    - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | tee /etc/apt/sources.list.d/docker.list > /dev/null
    - apt-get update && apt-get install docker-ce-cli -y
    - readonly ROOT_DIR="$(pwd)"
    - readonly BIN_DIR="${ROOT_DIR}/.bin"
    - readonly BUILD_DIR="${ROOT_DIR}/build"
    - readonly VERSION="3.0.0"
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
    - ./scripts/package.sh --version "$VERSION"
    - ${BIN_DIR}/pack buildpack package ${CI_REGISTRY_IMAGE}:${VERSION} --path "${BUILD_DIR}/buildpack.tgz" --format image
    - docker image push ${CI_REGISTRY_IMAGE}:${VERSION}
  tags: ["sandbox", "us-east-1", "docker-readonly", "aws"]
  when: manual
